### ISSUE TITLE
fragmented molecule atom mapping rearrangement

### ISSUE THREAD

**Issue by ldamore** [openforcefield/openff-fragmenter#126]
I found that the atom mapping of the fragmented molecule is rearranged with respect to the parent molecule. Could this be avoided? Or should this be documented?

**Comment by jthorton** [comment]
Hi @ldamore, are you saying that the input to fragment molecule mapping is not correct? If so this is often due to the input molecule being put into canonical order during fragmentation, this is needed to make fragmentation reproducible as conformer generation has been shown to depend on atom ordering. When comparing a fragment to a parent you should instead remake the parent from the `FragmentationResult`  class, using the property [here](https://github.com/openforcefield/openff-fragmenter/blob/3d8a5e20379cbfabada141c272fbdc8e69390e44/openff/fragmenter/fragment.py#L85). Note that the mapping also corresponds to map indices and not the actual atom indices, so an atom that is in both the parent and the fragment will have the same map index but a different particle index. You can see that in in the [docs](https://fragmenter.readthedocs.io/en/latest/fragment-molecules.html) in the results of box 3 and 4.

**Comment by j-wags** [comment]
Thanks @jthorton -- That's a great explanation and it helped unblock us! 

After working with @ldamore today, I realized that what we really want is a mapping from the input molecule to the parent. So I've opened https://github.com/openforcefield/openff-fragmenter/issues/129, which is blocked by the toolkit for the time being. But I think we can call this issue closed!
